### ISSUE TITLE
장르, 성우, 원작자, 제작사, 시리즈 삭제 수정

### ISSUE THREAD

**Issue by jaycobcoder** [oduck-team/oduck-server#102]
## 📝 개요
- 장르, 성우, 원작자, 제작사, 시리즈 유니크 제약조건 제거
- 삭제했을 때 애니와 연관 관계 제거
- 삭제된 장르, 성우, 원작자, 제작사, 시리즈와 동일한 이름이나 제목으로 등록하려고 할 때 등록 되도록 변경

## ✅ TODO
- [x] 장르, 성우, 원작자, 제작사, 시리즈 유니크 제약조건 제거
- [x] 삭제했을 때 애니와 연관 관계 제거
- [x] 삭제된 장르, 성우, 원작자, 제작사, 시리즈와 동일한 이름이나 제목으로 등록하려고 할 때 등록 되도록 변경
## 💬 기타
