### ISSUE TITLE
별점 평가 여부 조회시 점수도 포함하도록 수정

### ISSUE THREAD

**Issue by FaberJoo** [oduck-team/oduck-server#103]
## 📝 개요
별점 평가 여부 조회시 점수도 포함하도록 수정

## ✅ TODO
- [x] 별점 평가 여부 조회 DTO 
- [x] 별점 평가 여부 조회 서비스 
- [x] 별점 평가 여부 조회 테스트 수정
