### ISSUE TITLE
로컬 로그인 및 인증 도메인 구현하기

### ISSUE THREAD

**Issue by FaberJoo** [oduck-team/oduck-server#13]
## 📝 개요
스프링 시큐리티 로컬 로그인 구현하기

## ✅ TODO
- [x]  로컬(ID, PWD) 로그인 구현하기
- [x] 인증 상태(/auth/status) 요청 구현하기
- [x] 인증 테스트 작성하기

## 💬 기타
