### ISSUE TITLE
주간 인기 애니 조회

### ISSUE THREAD

**Issue by FaberJoo** [oduck-team/oduck-server#140]
## 📝 개요
주간 인기 애니 조회

## ✅ TODO
- [x] 주간 인기 애니 엔티티 추가
- [x] 핸들러 추가
- [x] service 로직 추가
- [x] repository 로직 추가
