### ISSUE TITLE
애니 연관 관계 설정

### ISSUE THREAD

**Issue by jaycobcoder** [oduck-team/oduck-server#16]
## ✅ TODO
- [ ] 애니 연관 관계 설정 메소드
- [ ] 북마크 작성 및 삭제 시 관련 메소드
- [ ] 리뷰 작성 및 삭제 시 관련 메소드

## 💬 기타
