### ISSUE TITLE
회원 도메인 구현

### ISSUE THREAD

**Issue by FaberJoo** [oduck-team/oduck-server#22]
## 📝 개요
회원 도메인구현

## ✅ TODO
- [x] 회원 프로필 조회
- [x] 회원 프로필 조회 테스트
- [x] 회원 프로필 수정
- [x] 회원 프로필 수정 테스트
- [x] 회원 입덕(북마크) 애니 목록 조회
- [x] 회원 입덕 애니 목록 조회 테스트

## 💬 기타

리뷰는 리뷰 도메인 작업 후 구현
