### ISSUE TITLE
북마크 도메인 구현

### ISSUE THREAD

**Issue by FaberJoo** [oduck-team/oduck-server#26]
## 📝 개요
북마크 도메인 구현

## ✅ TODO
- [x] 북마크(생성 및 삭제)
- [x] 북마크 테스트
- [x] 북마크 여부 조회
- [x] 북마크 여부 조회 테스트

## 💬 기타
