### ISSUE TITLE
애니 상세 조회 구현

### ISSUE THREAD

**Issue by jaycobcoder** [oduck-team/oduck-server#38]
## ✅ TODO
- [ ] 애니 상세 조회 리포지토리 구현
- [ ] 애니 상세 조회 서비스 구현
- [ ] 애니 상세 조회 컨트롤러 구현

## 💬 기타
