### ISSUE TITLE
애니 관련 도메인 등록

### ISSUE THREAD

**Issue by jaycobcoder** [oduck-team/oduck-server#39]
## ✅ TODO
- [x] 애니 관련 도메인 등록 리포지토리 구현
- [x] 애니 관련 도메인 등록 서비스 구현
- [x] 애니 관련 도메인 등록 컨트롤러 구현

## 💬 기타
