### ISSUE TITLE
Member Stub 문서화

### ISSUE THREAD

**Issue by FaberJoo** [oduck-team/oduck-server#5]
## 📝 개요
Member Stub 문서화

## ✅ TODO
- [x] Member Controller 생성
- [x] Member Dto 생성
- [x] Member ServiceStub 생성
- [x] Member Controller Test 생성

## 💬 기타
