### ISSUE TITLE
애니 삭제 구현 

### ISSUE THREAD

**Issue by jaycobcoder** [oduck-team/oduck-server#52]
## ✅ TODO
- [ ] 애니 삭제 컨트롤러 구현 및 문서화
- [ ] 애니 삭제 서비스 구현
- [ ] 애니 삭제 리포지토리 구현

## 💬 기타
